<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WaliSiswa;

class GuardianSeeder extends Seeder
{
    public function run()
    {
        $guardians = [
            [
                'siswa_id' => 1,
                'wali' => 'Ahmad Fikri',
                'nik_ayah' => '3201011234567890',
                'nama_ayah' => 'Ahmad Yani',
                'status_ayah' => 'Hidup',
                'tempat_lahir_ayah' => 'Bandung',
                'tanggal_lahir_ayah' => '1975-06-10',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'PNS',
                'penghasilan_ayah' => '5000000',
                'handphone_ayah' => '081234567890',
                'nik_ibu' => '3201011234567891',
                'nama_ibu' => 'Siti Fatimah',
                'status_ibu' => 'Hidup',
                'tempat_lahir_ibu' => 'Jakarta',
                'tanggal_lahir_ibu' => '1977-08-15',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Guru/Dosen',
                'penghasilan_ibu' => '4500000',
                'handphone_ibu' => '081234567891',
            ],
            [
                'siswa_id' => 2,
                'wali' => 'Budi Santoso',
                'nik_ayah' => null,
                'nama_ayah' => null,
                'status_ayah' => null,
                'tempat_lahir_ayah' => null,
                'tanggal_lahir_ayah' => null,
                'agama_ayah' => null,
                'pekerjaan_ayah' => null,
                'penghasilan_ayah' => null,
                'handphone_ayah' => null,
                'nik_ibu' => null,
                'nama_ibu' => null,
                'status_ibu' => null,
                'tempat_lahir_ibu' => null,
                'tanggal_lahir_ibu' => null,
                'agama_ibu' => null,
                'pekerjaan_ibu' => null,
                'penghasilan_ibu' => null,
                'handphone_ibu' => null,
                'nik_wali' => '3201011234567892',
                'nama_wali' => 'Agus Salim',
                'tempat_lahir_wali' => 'Surabaya',
                'tanggal_lahir_wali' => '1980-05-12',
                'agama_wali' => 'Islam',
                'pekerjaan_wali' => 'Pedagang',
                'penghasilan_wali' => '3000000',
                'handphone_wali' => '081234567892',
            ],
            [
                'siswa_id' => 3,
                'wali' => 'Siti Aminah',
                'nik_ayah' => '3201011234567893',
                'nama_ayah' => 'Joko Widodo',
                'status_ayah' => 'Hidup',
                'tempat_lahir_ayah' => 'Surabaya',
                'tanggal_lahir_ayah' => '1970-03-22',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'Wiraswasta',
                'penghasilan_ayah' => '7000000',
                'handphone_ayah' => '081234567893',
                'nik_ibu' => '3201011234567894',
                'nama_ibu' => 'Megawati Soekarnoputri',
                'status_ibu' => 'Hidup',
                'tempat_lahir_ibu' => 'Surabaya',
                'tanggal_lahir_ibu' => '1972-01-10',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Dokter/Bidan/Perawat',
                'penghasilan_ibu' => '0',
                'handphone_ibu' => '081234567894',
            ],
            [
                'siswa_id' => 4,
                'wali' => 'Dewi Sartika',
                'nik_ayah' => '3201011234567895',
                'nama_ayah' => 'Soeharto',
                'status_ayah' => 'Hidup',
                'tempat_lahir_ayah' => 'Medan',
                'tanggal_lahir_ayah' => '1968-11-30',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'PNS',
                'penghasilan_ayah' => '6000000',
                'handphone_ayah' => '081234567895',
                'nik_ibu' => '3201011234567896',
                'nama_ibu' => 'Iriana Soekarnoputri',
                'status_ibu' => 'Hidup',
                'tempat_lahir_ibu' => 'Medan',
                'tanggal_lahir_ibu' => '1970-09-05',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Wiraswasta',
                'penghasilan_ibu' => '4000000',
                'handphone_ibu' => '081234567896',
            ],
            [
                'siswa_id' => 5,
                'wali' => 'Rizky Hidayat',
                'nik_ayah' => null,
                'nama_ayah' => null,
                'status_ayah' => null,
                'tempat_lahir_ayah' => null,
                'tanggal_lahir_ayah' => null,
                'agama_ayah' => null,
                'pekerjaan_ayah' => null,
                'penghasilan_ayah' => null,
                'handphone_ayah' => null,
                'nik_ibu' => null,
                'nama_ibu' => null,
                'status_ibu' => null,
                'tempat_lahir_ibu' => null,
                'tanggal_lahir_ibu' => null,
                'agama_ibu' => null,
                'pekerjaan_ibu' => null,
                'penghasilan_ibu' => null,
                'handphone_ibu' => null,
                'nik_wali' => '3201011234567897',
                'nama_wali' => 'Hendra Gunawan',
                'tempat_lahir_wali' => 'Yogyakarta',
                'tanggal_lahir_wali' => '1982-04-15',
                'agama_wali' => 'Islam',
                'pekerjaan_wali' => 'Nelayan',
                'penghasilan_wali' => '3500000',
                'handphone_wali' => '081234567897',
            ],
            [
                'siswa_id' => 6,
                'wali' => 'Lia Wulandari',
                'nik_ayah' => '3201011234567898',
                'nama_ayah' => 'Sudirman',
                'status_ayah' => 'Hidup',
                'tempat_lahir_ayah' => 'Semarang',
                'tanggal_lahir_ayah' => '1965-02-20',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'PNS',
                'penghasilan_ayah' => '5500000',
                'handphone_ayah' => '081234567898',
                'nik_ibu' => '3201011234567899',
                'nama_ibu' => 'Siti Nurhaliza',
                'status_ibu' => 'Hidup',
                'tempat_lahir_ibu' => 'Semarang',
                'tanggal_lahir_ibu' => '1967-07-25',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Dokter/Bidan/Perawat',
                'penghasilan_ibu' => '9000000',
                'handphone_ibu' => '081234567899',
            ],
            [
                'siswa_id' => 7,
                'wali' => 'Agus Salim',
                'nik_ayah' => null,
                'nama_ayah' => null,
                'status_ayah' => null,
                'tempat_lahir_ayah' => null,
                'tanggal_lahir_ayah' => null,
                'agama_ayah' => null,
                'pekerjaan_ayah' => null,
                'penghasilan_ayah' => null,
                'handphone_ayah' => null,
                'nik_ibu' => null,
                'nama_ibu' => null,
                'status_ibu' => null,
                'tempat_lahir_ibu' => null,
                'tanggal_lahir_ibu' => null,
                'agama_ibu' => null,
                'pekerjaan_ibu' => null,
                'penghasilan_ibu' => null,
                'handphone_ibu' => null,
                'nik_wali' => '3201011234567800',
                'nama_wali' => 'Mahmud Arif',
                'tempat_lahir_wali' => 'Palembang',
                'tanggal_lahir_wali' => '1984-08-08',
                'agama_wali' => 'Islam',
                'pekerjaan_wali' => 'Nelayan',
                'penghasilan_wali' => '2500000',
                'handphone_wali' => '081234567800',
            ],
            [
                'siswa_id' => 8,
                'wali' => 'Indah Permata',
                'nik_ayah' => '3201011234567801',
                'nama_ayah' => 'Raden Saleh',
                'status_ayah' => 'Hidup',
                'tempat_lahir_ayah' => 'Bandung',
                'tanggal_lahir_ayah' => '1978-05-18',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'Seniman/Pelukis/Artis/Sejenis',
                'penghasilan_ayah' => '6000000',
                'handphone_ayah' => '081234567801',
                'nik_ibu' => '3201011234567802',
                'nama_ibu' => 'Kartini',
                'status_ibu' => 'Hidup',
                'tempat_lahir_ibu' => 'Bandung',
                'tanggal_lahir_ibu' => '1980-02-28',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Pengacara/Jaksa/Hakim/Notaris',
                'penghasilan_ibu' => '8500000',
                'handphone_ibu' => '081234567802',
            ],
            [
                'siswa_id' => 9,
                'wali' => 'Fajar Nugraha',
                'nik_ayah' => '3201011234567803',
                'nama_ayah' => 'Bambang Pamungkas',
                'status_ayah' => 'Hidup',
                'tempat_lahir_ayah' => 'Makassar',
                'tanggal_lahir_ayah' => '1972-10-05',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'Atlet',
                'penghasilan_ayah' => '10000000',
                'handphone_ayah' => '081234567803',
                'nik_ibu' => '3201011234567804',
                'nama_ibu' => 'Wina Natalia',
                'status_ibu' => 'Hidup',
                'tempat_lahir_ibu' => 'Makassar',
                'tanggal_lahir_ibu' => '1974-12-22',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Dosen',
                'penghasilan_ibu' => '5000000',
                'handphone_ibu' => '081234567804',
            ],
            [
                'siswa_id' => 10,
                'wali' => 'Rina Wijaya',
                'nik_ayah' => null,
                'nama_ayah' => null,
                'status_ayah' => null,
                'tempat_lahir_ayah' => null,
                'tanggal_lahir_ayah' => null,
                'agama_ayah' => null,
                'pekerjaan_ayah' => null,
                'penghasilan_ayah' => null,
                'handphone_ayah' => null,
                'nik_ibu' => null,
                'nama_ibu' => null,
                'status_ibu' => null,
                'tempat_lahir_ibu' => null,
                'tanggal_lahir_ibu' => null,
                'agama_ibu' => null,
                'pekerjaan_ibu' => null,
                'penghasilan_ibu' => null,
                'handphone_ibu' => null,
                'nik_wali' => '3201011234567805',
                'nama_wali' => 'Syarif Hidayat',
                'tempat_lahir_wali' => 'Denpasar',
                'tanggal_lahir_wali' => '1983-11-11',
                'agama_wali' => 'Islam',
                'pekerjaan_wali' => 'Sopir/Masinis/Kondektur',
                'penghasilan_wali' => '4000000',
                'handphone_wali' => '081234567805',
            ],
        ];

        foreach ($guardians as $guardian) {
            WaliSiswa::create($guardian);
        }
    }
}
