<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Guru;

class GuruSeeder extends Seeder
{
    public function run()
    {
        $gurus = [
            [
                'nip' => 1234567890123,
                'nuptk' => 9876543210123,
                'nama' => 'Ahmad Fauzi',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-04-15',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '01/02',
                'Kelurahan' => '5310081004',
                'foto' => 'ahmad_fauzi.jpg',
            ],
            [
                'nip' => 1234567890124,
                'nuptk' => 9876543210124,
                'nama' => 'Budi Santoso',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-07-22',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '02/03',
                'Kelurahan' => '5310081004',
                'foto' => 'budi_santoso.jpg',
            ],
            [
                'nip' => 1234567890125,
                'nuptk' => 9876543210125,
                'nama' => 'Siti Aminah',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1979-05-30',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '03/04',
                'Kelurahan' => '5310081004',
                'foto' => 'siti_aminah.jpg',
            ],
            [
                'nip' => 1234567890126,
                'nuptk' => 9876543210126,
                'nama' => 'Joko Widodo',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1982-08-11',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '04/05',
                'Kelurahan' => '5310081004',
                'foto' => 'joko_widodo.jpg',
            ],
            [
                'nip' => 1234567890127,
                'nuptk' => 9876543210127,
                'nama' => 'Lia Wulandari',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1987-09-17',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '05/06',
                'Kelurahan' => '5310081004',
                'foto' => 'lia_wulandari.jpg',
            ],
            [
                'nip' => 1234567890128,
                'nuptk' => 9876543210128,
                'nama' => 'Agus Salim',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1983-03-25',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '06/07',
                'Kelurahan' => '5310081004',
                'foto' => 'agus_salim.jpg',
            ],
            [
                'nip' => 1234567890129,
                'nuptk' => 9876543210129,
                'nama' => 'Indah Permata',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-04-05',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '07/08',
                'Kelurahan' => '5310081004',
                'foto' => 'indah_permata.jpg',
            ],
            [
                'nip' => 1234567890130,
                'nuptk' => 9876543210130,
                'nama' => 'Fajar Nugraha',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1986-11-20',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '08/09',
                'Kelurahan' => '5310081004',
                'foto' => 'fajar_nugraha.jpg',
            ],
            [
                'nip' => 1234567890131,
                'nuptk' => 9876543210131,
                'nama' => 'Rina Wijaya',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '1984-12-30',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '09/10',
                'Kelurahan' => '5310081004',
                'foto' => 'rina_wijaya.jpg',
            ],
            [
                'nip' => 1234567890132,
                'nuptk' => 9876543210132,
                'nama' => 'Dewi Sartika',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-06-15',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '10/11',
                'Kelurahan' => '5310081004',
                'foto' => 'dewi_sartika.jpg',
            ],
            [
                'nip' => 1234567890133,
                'nuptk' => 9876543210133,
                'nama' => 'Rizky Hidayat',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '1989-02-22',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '11/12',
                'Kelurahan' => '5310081004',
                'foto' => 'rizky_hidayat.jpg',
            ],
            [
                'nip' => 1234567890134,
                'nuptk' => 9876543210134,
                'nama' => 'Agung Prabowo',
                'tempat_lahir' => 'Surakarta',
                'tanggal_lahir' => '1981-07-12',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '12/13',
                'Kelurahan' => '5310081004',
                'foto' => 'agung_prabowo.jpg',
            ],
            [
                'nip' => 1234567890135,
                'nuptk' => 9876543210135,
                'nama' => 'Maya Sari',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1988-09-20',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Sepuran, Kecamatan Alok Barat, Kabupaten Sikka',
                'rt_rw' => '13/14',
                'Kelurahan' => '5310081004',
                'foto' => 'maya_sari.jpg',
            ],
        ];

        foreach ($gurus as $guru) {
            Guru::create($guru);
        }
    }
}
